# Configuration for welcome - https://github.com/behaviorbot/welcome

# Configuration for new-issue-welcome - https://github.com/behaviorbot/new-issue-welcome

# Comment to be posted to on first time issues
newIssueWelcomeComment: >
  Hello there! ğŸ‘‹ Welcome to this project! ğŸ’–

  Thanks for opening your first issue here! ğŸ‰ğŸ‰
  Don't forget to star this repo to stay updated! ğŸ˜„

# Configuration for new-pr-welcome - https://github.com/behaviorbot/new-pr-welcome

# Comment to be posted to on PRs from first time contributors in your repository
newPRWelcomeComment: >
  Hello there! ğŸ‘‹ Welcome to this project! ğŸ’–

  Thank you and congrats ğŸ‰ğŸ‰ for opening your first pull request! âœ¨
  Don't forget to star â­ this repo to stay updated! ğŸ˜„

# Configuration for first-pr-merge - https://github.com/behaviorbot/first-pr-merge

# Comment to be posted to on pull requests merged by a first time user
firstPRMergeComment: >
  Congrats on merging your first pull request! ğŸ‰ğŸ‰

# It is recommend to include as many gifs and emojis as possible
